/*
 * keygen_tool.c -- build-time ML-KEM-1024 "encryption" of the unlock key.
 *
 * 1. m = SHAKE256(CORRECT_KEY)            (32 bytes)
 * 2. (pk, sk) = ML-KEM-1024.KeyGen()
 * 3. (ct, ss) = ML-KEM-1024.Encaps(pk)
 * 4. check   = m XOR ss                   (Hybrid Encryption, ECIES-style)
 *
 * Emits keyblob.h containing sk, ct and check.  The plaintext key is NOT
 * written anywhere in the output -- only the ML-KEM-1024 ciphertext + the
 * decapsulation key remain in the built program.
 *
 * At runtime the app recomputes the same derivation and only closes when
 *  SHAKE256(user_input) XOR ML-KEM-1024.Decaps(sk, ct) == check.
 */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "api.h"
#include "fips202.h"
#include "key_secret.h"

#define M_SIZE 32

static void print_arr(const char *name, const uint8_t *a, size_t n) {
    size_t i;
    printf("static const uint8_t %s[%zu] = {\n    ", name, n);
    for (i = 0; i < n; i++) {
        printf("0x%02x", a[i]);
        if (i + 1 < n) {
            printf(", ");
        }
        if ((i + 1) % 12 == 0) {
            printf("\n    ");
        }
    }
    printf("\n};\n");
}

static int key_matches(const char *str,
                       const uint8_t ct[PQCLEAN_MLKEM1024_CLEAN_CRYPTO_CIPHERTEXTBYTES],
                       const uint8_t sk[PQCLEAN_MLKEM1024_CLEAN_CRYPTO_SECRETKEYBYTES],
                       const uint8_t check[M_SIZE]) {
    uint8_t m[M_SIZE], ss[M_SIZE], c[M_SIZE];
    size_t len;
    int i;

    len = strlen(str);
    shake256(m, M_SIZE, (const uint8_t *)str, len);
    PQCLEAN_MLKEM1024_CLEAN_crypto_kem_dec(ss, ct, sk);
    for (i = 0; i < M_SIZE; i++) {
        c[i] = (uint8_t)(m[i] ^ ss[i]);
    }
    for (i = 0; i < M_SIZE; i++) {
        if (c[i] != check[i]) {
            return 0;
        }
    }
    return 1;
}

int main(void) {
    uint8_t pk[PQCLEAN_MLKEM1024_CLEAN_CRYPTO_PUBLICKEYBYTES];
    uint8_t sk[PQCLEAN_MLKEM1024_CLEAN_CRYPTO_SECRETKEYBYTES];
    uint8_t ct[PQCLEAN_MLKEM1024_CLEAN_CRYPTO_CIPHERTEXTBYTES];
    uint8_t ss[PQCLEAN_MLKEM1024_CLEAN_CRYPTO_BYTES];
    uint8_t m[M_SIZE], check[M_SIZE];
    int i;

    shake256(m, M_SIZE, (const uint8_t *)CORRECT_KEY, strlen(CORRECT_KEY));

    if (PQCLEAN_MLKEM1024_CLEAN_crypto_kem_keypair(pk, sk)) {
        fprintf(stderr, "keygen failed\n");
        return 2;
    }
    if (PQCLEAN_MLKEM1024_CLEAN_crypto_kem_enc(ct, ss, pk)) {
        fprintf(stderr, "encapsulation failed\n");
        return 3;
    }
    for (i = 0; i < M_SIZE; i++) {
        check[i] = (uint8_t)(m[i] ^ ss[i]);
    }

    /* Self-check: the exact runtime path must accept the real key and
     * reject a wrong one. This validates the whole pipeline. */
    if (!key_matches(CORRECT_KEY, ct, sk, check)) {
        fprintf(stderr, "SELF-CHECK FAILED: real key was rejected\n");
        return 4;
    }
    if (key_matches("definitely-the-wrong-key-000", ct, sk, check)) {
        fprintf(stderr, "SELF-CHECK FAILED: wrong key was accepted\n");
        return 5;
    }
    fprintf(stderr,
            "self-check OK: %zu-byte key encrypted with ML-KEM-1024\n",
            strlen(CORRECT_KEY));

    printf("/* Auto-generated by keygen_tool.exe -- do not edit. */\n");
    printf("/* Unlock key encrypted with ML-KEM-1024 (see key_secret.h). */\n");
    printf("#ifndef KEYBLOB_H\n");
    printf("#define KEYBLOB_H\n");
    printf("#include <stdint.h>\n");
    print_arr("KEYBLOB_SK", sk, sizeof sk);
    print_arr("KEYBLOB_CT", ct, sizeof ct);
    print_arr("KEYBLOB_CHECK", check, sizeof check);
    printf("#endif /* KEYBLOB_H */\n");
    return 0;
}